* imap-filter
  imap-filter is a Ruby implementation of an IMAP filtering application.
  it can handle multiple IMAP accounts, and create IMAP folders automatically
  where none exists.

  The imap-filter DSL makes it easy to filter. You can also do "dry-runs"
  to make sure what happens is what is expected.
** Installation
   This is a Ruby CLI application. If you are running Linux, most likely
   you have Ruby already installed. If you are running MacOSX or Windows,
   you may have to Install Ruby. We support Ruby 2.2 and later.

   Simply, do:

   #+begin_src bash
   gem install 
   #+end_src

** Documentation
*** Accessing your Gmail
    Google may automatically block this application by default.
    Please visit the follow page to understand how to allow 
    imap-filter to access your Gmail account.

    https://support.google.com/accounts/answer/6010255

*** DSL
    #+begin_src Ruby
    account :redbird do
      login "you@redbird.org", "password"
      serv "imap.redbird.org"
      ssl false
      port 993
    end

    account :yahoo do
      login "you@yahoo.com", "password"
      serv "imap.yahoo.com"
    end

    account :google do
      login "you@google.com", "password"
      serv "imap.google.com"
    end

    filter :workmail, redbird.inbox, from: 'sally' do
      cp yahoo.girlfriend
      mv google.inbox
    end

    filter :maillist, google.inbox, from: 'github' do
      mv google.groups.github
    end

    #+end_src

*** Reference Documents
    https://tools.ietf.org/html/rfc3501
    https://www.ietf.org/rfc/rfc2822.txt


** Contributing to imap-filter

   |   | Check out the latest master to make sure the feature hasn't been implemented or the bug hasn't been fixed yet.                                                                                                     |
   |   | Check out the issue tracker to make sure someone already hasn't requested it and/or contributed it.                                                                                                                |
   |   | Fork the project.                                                                                                                                                                                                  |
   |   | Start a feature/bugfix branch.                                                                                                                                                                                     |
   |   | Commit and push until you are happy with your contribution.                                                                                                                                                        |
   |   | Make sure to add tests for it. This is important so I don't break it in a future version unintentionally.                                                                                                          |
   |   | Please try not to mess with the Rakefile, version, or history. If you want to have your own version, or is otherwise necessary, that is fine, but please isolate to its own commit so I can cherry-pick around it. |

** Copyright

   Copyright (c) 2016 Fred Mitchell. See LICENSE.txt for
   further details.

** Scratchpad
   This section is my personal scratchpad. Should be of
   no revelance to anyone else. Please ignore what's in
   this section.
*** Raw login
    imap = Net::IMAP.new('imap.gmail.com', ssl: true) 
    imap.authenticate('PLAIN', ENV['GOOGLE_EMAIL'], ENV['GOOGLE_PASS'])
    imap.select('Shelby')
    seq = imap.search(['ALL'])

*** FETCH
   acc.imap.fetch(1..2, 'BODY[TEXT]') -- the entire text, flags as well.
   acc.imap.fetch(1..2, 'BODY[HEADER.FIELDS (SUBJECT)]')
